language: csharp
solution: SolrExpress.sln
os: linux
dist: trusty
sudo: false
dotnet: 1.1.0
mono: none
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

branches:
  only:
    - master
    - v.5.0

script:
  - dotnet restore
  - dotnet test ./test/SolrExpress.UnitTests --verbosity minimal --framework "netcoreapp1.1" --configuration release
  - dotnet test ./test/SolrExpress.Solr4.UnitTests --verbosity minimal --framework "netcoreapp1.1" --configuration release
  - dotnet test ./test/SolrExpress.Solr5.UnitTests --verbosity minimal --framework "netcoreapp1.1" --configuration release