language: csharp
solution: SolrExpress.sln

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.1
      mono: none

branches:
  only:
    - master
    - v.5.0

script:
  - dotnet restore
  - dotnet test ./test/SolrExpress.UnitTests --verbosity minimal --framework "netcoreapp1.1"
  - dotnet test ./test/SolrExpress.Solr4.UnitTests --verbosity minimal --framework "netcoreapp1.1"
  - dotnet test ./test/SolrExpress.Solr5.UnitTests --verbosity minimal --framework "netcoreapp1.1"