language: csharp
solution: SolrExpress.sln
mono: none
dotnet: 1.1
dist: trusty
os: linux

branches:
  only:
    - master
    - v.5.0

script:
  - dotnet restore
  - dotnet test ./test/SolrExpress.UnitTests --verbosity minimal --framework "netcoreapp1.1"
  - dotnet test ./test/SolrExpress.Solr4.UnitTests --verbosity minimal --framework "netcoreapp1.1"
  - dotnet test ./test/SolrExpress.Solr5.UnitTests --verbosity minimal --framework "netcoreapp1.1"